name: Shing Lyu
highlighter: rouge
markdown: kramdown
exclude_pages: ["Hi! I'm Shing Lyu", "JCMG Corpus", "RSS", "Blog", "Privacy Policy"]
include: [".well-known"]
description: Shing Lyu's Portfolio and Blog
url: https://shinglyu.com
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      css: "/css/post.css"
      layout: post
